# Generated by Django 6.0.5 on 2026-06-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(default='', max_length=1000)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='img/menu_items')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('reservation_count', models.PositiveIntegerField()),
                ('reservation_date', models.DateTimeField(auto_now=True)),
                ('comments', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
